import type { WoodFinish, GroutOption, PresetProject } from '../types/configurator';

export const WOOD_FINISHES: WoodFinish[] = [
  {
    id: 'natural-oak',
    name: 'Stejar Scandinav Natural',
    description: 'Nuanțe calde de stejar auriu cu inserții subtile de fibră din beton',
    primaryColor: '#c8a27a',
    secondaryColor: '#b08a62',
    grainColor: '#6e4f35',
    poreColor: '#543b27',
    previewGradient: 'linear-gradient(135deg, #d8b48c 0%, #b88d64 100%)',
  },
  {
    id: 'dark-walnut',
    name: 'Nuc Închis Russet',
    description: 'Textură profundă de nuc espresso cu caracter rustic bogat',
    primaryColor: '#4a3525',
    secondaryColor: '#382619',
    grainColor: '#21150c',
    poreColor: '#140c07',
    previewGradient: 'linear-gradient(135deg, #5c4331 0%, #302014 100%)',
  },
  {
    id: 'driftwood-gray',
    name: 'Lemn Patinat Gri de Plajă',
    description: 'Aspect de lemn argintiu patinat, ideal pentru terase moderne',
    primaryColor: '#93989c',
    secondaryColor: '#7a8085',
    grainColor: '#4f5458',
    poreColor: '#36393c',
    previewGradient: 'linear-gradient(135deg, #a3a8ac 0%, #686d71 100%)',
  },
  {
    id: 'smoked-pine',
    name: 'Cedru & Molid Afumat',
    description: 'Miere maronie medie cu inele pronunțate de lemn închis',
    primaryColor: '#9e6d42',
    secondaryColor: '#82552d',
    grainColor: '#4d3016',
    poreColor: '#36200d',
    previewGradient: 'linear-gradient(135deg, #af7d50 0%, #6b4320 100%)',
  },
  {
    id: 'weathered-teak',
    name: 'Tec Blond Albire Solară',
    description: 'Tonalitate eleganta de chihlimbar deschis cu luciu satinat',
    primaryColor: '#d6aa75',
    secondaryColor: '#bd8e57',
    grainColor: '#7e5a32',
    poreColor: '#5c4021',
    previewGradient: 'linear-gradient(135deg, #e4ba85 0%, #a47640 100%)',
  },
  {
    id: 'raw-concrete',
    name: 'Beton Industrial Antracit',
    description: 'Beton arhitectural cu relief fin de cofraj din scândură',
    primaryColor: '#5c6066',
    secondaryColor: '#484c52',
    grainColor: '#2b2e33',
    poreColor: '#1d1f22',
    previewGradient: 'linear-gradient(135deg, #6c7178 0%, #3a3d42 100%)',
  },
];

export const GROUT_OPTIONS: GroutOption[] = [
  { id: 'anthracite', name: 'Gri Închis Antracit', color: '#2b2b30' },
  { id: 'cement-gray', name: 'Gri Ciment Standard', color: '#7a7d85' },
  { id: 'beige-sand', name: 'Nisip Bej Cald', color: '#c4b59b' },
  { id: 'light-silver', name: 'Gri Argintiu Deschis', color: '#b5b9c0' },
  { id: 'charcoal-black', name: 'Negru Cărbune', color: '#18191c' },
];

export const PRESET_PROJECTS: PresetProject[] = [
  {
    id: 'herringbone-120-600',
    title: 'Alee Brăduț 120×600 cm',
    description: '7.2 m² (1.2m × 6.0m) țesătură Brăduț 90° cu dale de 60×20 cm din Stejar',
    area: 7.2,
    shape: 'rectangle',
    dimensions: { length: 6.0, width: 1.2 },
    pattern: 'herringbone-90',
    woodFinishId: 'natural-oak',
    iconName: 'Footprints',
  },
  {
    id: 'patio-15',
    title: 'Terasă Dining Compactă',
    description: '15 m² (5m × 3m) model Brăduț 90° cu Stejar Scandinav',
    area: 15,
    shape: 'rectangle',
    dimensions: { length: 5, width: 3 },
    pattern: 'herringbone-90',
    woodFinishId: 'natural-oak',
    iconName: 'Coffee',
  },
  {
    id: 'terrace-28',
    title: 'Terasă Jardin Apus',
    description: '28 m² (7m × 4m) model Brăduț Diagonal 45° cu Lemn Patinat Gri',
    area: 28,
    shape: 'rectangle',
    dimensions: { length: 7, width: 4 },
    pattern: 'herringbone-45',
    woodFinishId: 'driftwood-gray',
    iconName: 'Sun',
  },
  {
    id: 'pool-deck-45',
    title: 'Plajă Piscină Modernă',
    description: '45 m² (9m × 5m) model Brăduț 90° cu Tec Blond',
    area: 45,
    shape: 'rectangle',
    dimensions: { length: 9, width: 5 },
    pattern: 'herringbone-90',
    woodFinishId: 'weathered-teak',
    iconName: 'Waves',
  },
  {
    id: 'courtyard-75',
    title: 'Curte Conac Mare',
    description: '75 m² (10m × 7.5m) model Brăduț Diagonal 45° cu Molid Afumat',
    area: 75,
    shape: 'rectangle',
    dimensions: { length: 10, width: 7.5 },
    pattern: 'herringbone-45',
    woodFinishId: 'smoked-pine',
    iconName: 'Home',
  },
];
